from django.core.management.base import BaseCommand
from apps.api.models import Achievement


class Command(BaseCommand):
    help = '기본 업적 20개 생성'

    def handle(self, *args, **options):
        achievements = [
            # 운동 카테고리
            {
                'name': '첫 걸음',
                'name_en': 'First Step',
                'name_es': 'Primer Paso',
                'description': '첫 운동 완료',
                'description_en': 'Complete your first workout',
                'description_es': 'Completa tu primer entrenamiento',
                'category': 'workout',
                'badge_level': 'bronze',
                'icon_name': 'fitness_center',
                'target_value': 1,
                'points': 10,
            },
            {
                'name': '운동 중독자',
                'name_en': 'Workout Addict',
                'name_es': 'Adicto al Ejercicio',
                'description': '10회 운동 완료',
                'description_en': 'Complete 10 workouts',
                'description_es': 'Completa 10 entrenamientos',
                'category': 'workout',
                'badge_level': 'silver',
                'icon_name': 'fitness_center',
                'target_value': 10,
                'points': 25,
            },
            {
                'name': '피트니스 전사',
                'name_en': 'Fitness Warrior',
                'name_es': 'Guerrero del Fitness',
                'description': '50회 운동 완료',
                'description_en': 'Complete 50 workouts',
                'description_es': 'Completa 50 entrenamientos',
                'category': 'workout',
                'badge_level': 'gold',
                'icon_name': 'fitness_center',
                'target_value': 50,
                'points': 50,
            },
            {
                'name': '운동의 왕',
                'name_en': 'King of Exercise',
                'name_es': 'Rey del Ejercicio',
                'description': '100회 운동 완료',
                'description_en': 'Complete 100 workouts',
                'description_es': 'Completa 100 entrenamientos',
                'category': 'workout',
                'badge_level': 'platinum',
                'icon_name': 'fitness_center',
                'target_value': 100,
                'points': 100,
            },
            # 영양 카테고리
            {
                'name': '영양 관리 시작',
                'name_en': 'Nutrition Start',
                'name_es': 'Inicio Nutricional',
                'description': '첫 식단 기록',
                'description_en': 'Record your first meal',
                'description_es': 'Registra tu primera comida',
                'category': 'nutrition',
                'badge_level': 'bronze',
                'icon_name': 'restaurant',
                'target_value': 1,
                'points': 10,
            },
            {
                'name': '균형 잡힌 식단',
                'name_en': 'Balanced Diet',
                'name_es': 'Dieta Equilibrada',
                'description': '7일 연속 식단 기록',
                'description_en': 'Record meals for 7 days in a row',
                'description_es': 'Registra comidas durante 7 días seguidos',
                'category': 'nutrition',
                'badge_level': 'silver',
                'icon_name': 'restaurant',
                'target_value': 7,
                'points': 30,
            },
            {
                'name': '영양 전문가',
                'name_en': 'Nutrition Expert',
                'name_es': 'Experto en Nutrición',
                'description': '30일 식단 기록 달성',
                'description_en': 'Record meals for 30 days',
                'description_es': 'Registra comidas durante 30 días',
                'category': 'nutrition',
                'badge_level': 'gold',
                'icon_name': 'restaurant',
                'target_value': 30,
                'points': 60,
            },
            # 연속 카테고리
            {
                'name': '3일 연속',
                'name_en': '3 Day Streak',
                'name_es': 'Racha de 3 Días',
                'description': '3일 연속 운동 완료',
                'description_en': 'Exercise for 3 days in a row',
                'description_es': 'Ejercita durante 3 días seguidos',
                'category': 'streak',
                'badge_level': 'bronze',
                'icon_name': 'whatshot',
                'target_value': 3,
                'points': 15,
            },
            {
                'name': '일주일 전사',
                'name_en': 'Week Warrior',
                'name_es': 'Guerrero Semanal',
                'description': '7일 연속 운동 완료',
                'description_en': 'Exercise for 7 days in a row',
                'description_es': 'Ejercita durante 7 días seguidos',
                'category': 'streak',
                'badge_level': 'silver',
                'icon_name': 'whatshot',
                'target_value': 7,
                'points': 35,
            },
            {
                'name': '월간 챔피언',
                'name_en': 'Monthly Champion',
                'name_es': 'Campeón Mensual',
                'description': '30일 연속 운동 완료',
                'description_en': 'Exercise for 30 days in a row',
                'description_es': 'Ejercita durante 30 días seguidos',
                'category': 'streak',
                'badge_level': 'gold',
                'icon_name': 'whatshot',
                'target_value': 30,
                'points': 75,
            },
            {
                'name': '100일의 기적',
                'name_en': '100 Day Miracle',
                'name_es': 'Milagro de 100 Días',
                'description': '100일 연속 운동 완료',
                'description_en': 'Exercise for 100 days in a row',
                'description_es': 'Ejercita durante 100 días seguidos',
                'category': 'streak',
                'badge_level': 'diamond',
                'icon_name': 'whatshot',
                'target_value': 100,
                'points': 200,
            },
            # 마일스톤 카테고리
            {
                'name': '1000칼로리 버너',
                'name_en': '1000 Calorie Burner',
                'name_es': 'Quemador de 1000 Calorías',
                'description': '총 1000칼로리 소모',
                'description_en': 'Burn a total of 1000 calories',
                'description_es': 'Quema un total de 1000 calorías',
                'category': 'milestone',
                'badge_level': 'bronze',
                'icon_name': 'local_fire_department',
                'target_value': 1000,
                'points': 20,
            },
            {
                'name': '5000칼로리 버너',
                'name_en': '5000 Calorie Burner',
                'name_es': 'Quemador de 5000 Calorías',
                'description': '총 5000칼로리 소모',
                'description_en': 'Burn a total of 5000 calories',
                'description_es': 'Quema un total de 5000 calorías',
                'category': 'milestone',
                'badge_level': 'silver',
                'icon_name': 'local_fire_department',
                'target_value': 5000,
                'points': 40,
            },
            {
                'name': '10000칼로리 버너',
                'name_en': '10000 Calorie Burner',
                'name_es': 'Quemador de 10000 Calorías',
                'description': '총 10000칼로리 소모',
                'description_en': 'Burn a total of 10000 calories',
                'description_es': 'Quema un total de 10000 calorías',
                'category': 'milestone',
                'badge_level': 'gold',
                'icon_name': 'local_fire_department',
                'target_value': 10000,
                'points': 80,
            },
            # 챌린지 카테고리
            {
                'name': '새벽형 인간',
                'name_en': 'Early Bird',
                'name_es': 'Madrugador',
                'description': '오전 6시 이전에 5회 운동',
                'description_en': 'Exercise 5 times before 6 AM',
                'description_es': 'Ejercita 5 veces antes de las 6 AM',
                'category': 'challenge',
                'badge_level': 'silver',
                'icon_name': 'alarm',
                'target_value': 5,
                'points': 30,
            },
            {
                'name': '주말 전사',
                'name_en': 'Weekend Warrior',
                'name_es': 'Guerrero de Fin de Semana',
                'description': '주말에 10회 운동',
                'description_en': 'Exercise 10 times on weekends',
                'description_es': 'Ejercita 10 veces en fines de semana',
                'category': 'challenge',
                'badge_level': 'silver',
                'icon_name': 'weekend',
                'target_value': 10,
                'points': 30,
            },
            {
                'name': '다양성의 달인',
                'name_en': 'Master of Variety',
                'name_es': 'Maestro de la Variedad',
                'description': '10가지 다른 운동 시도',
                'description_en': 'Try 10 different exercises',
                'description_es': 'Prueba 10 ejercicios diferentes',
                'category': 'challenge',
                'badge_level': 'gold',
                'icon_name': 'diversity_3',
                'target_value': 10,
                'points': 50,
            },
            {
                'name': '소셜 스타',
                'name_en': 'Social Star',
                'name_es': 'Estrella Social',
                'description': '운동 기록 10회 공유',
                'description_en': 'Share 10 workout records',
                'description_es': 'Comparte 10 registros de ejercicio',
                'category': 'challenge',
                'badge_level': 'silver',
                'icon_name': 'share',
                'target_value': 10,
                'points': 30,
            },
            {
                'name': '완벽주의자',
                'name_en': 'Perfectionist',
                'name_es': 'Perfeccionista',
                'description': '한 달 동안 모든 목표 달성',
                'description_en': 'Achieve all goals for one month',
                'description_es': 'Alcanza todos los objetivos durante un mes',
                'category': 'challenge',
                'badge_level': 'platinum',
                'icon_name': 'star',
                'target_value': 1,
                'points': 100,
            },
            {
                'name': '헬스 마스터',
                'name_en': 'Fitness Master',
                'name_es': 'Maestro del Fitness',
                'description': '레벨 50 달성',
                'description_en': 'Reach level 50',
                'description_es': 'Alcanza el nivel 50',
                'category': 'milestone',
                'badge_level': 'diamond',
                'icon_name': 'military_tech',
                'target_value': 50,
                'points': 150,
            },
        ]

        created_count = 0
        for achievement_data in achievements:
            achievement, created = Achievement.objects.update_or_create(
                name=achievement_data['name'],
                defaults=achievement_data
            )
            if created:
                created_count += 1
                self.stdout.write(self.style.SUCCESS(f'업적 생성: {achievement.name}'))
            else:
                self.stdout.write(self.style.WARNING(f'업적 업데이트: {achievement.name}'))

        self.stdout.write(self.style.SUCCESS(f'총 {created_count}개의 새로운 업적이 생성되었습니다.'))
