[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = [
    ". /opt/venv/bin/activate && python manage.py collectstatic --noinput",
    ". /opt/venv/bin/activate && python manage.py migrate --noinput || true"
]

[start]
cmd = ". /opt/venv/bin/activate && gunicorn healthwise.wsgi:application --bind 0.0.0.0:$PORT"

[variables]
NIXPACKS_PATH = "/opt/venv/bin:$NIXPACKS_PATH"