# Generated by Django 5.2.3 on 2025-06-26 15:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=100, verbose_name='운동 이름')),
                ('target_duration', models.IntegerField(blank=True, help_text='목표 운동 시간 (초)', null=True)),
                ('target_reps', models.IntegerField(blank=True, help_text='목표 반복 횟수', null=True)),
                ('target_score', models.FloatField(blank=True, help_text='목표 자세 점수', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('target_calories', models.FloatField(blank=True, help_text='목표 칼로리', null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '운동 목표',
                'verbose_name_plural': '운동 목표',
                'db_table': 'workout_goals',
                'unique_together': {('user', 'exercise_name', 'is_active')},
            },
        ),
        migrations.CreateModel(
            name='WorkoutResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=100, verbose_name='운동 이름')),
                ('exercise_type', models.CharField(choices=[('strength', '근력 운동'), ('cardio', '유산소 운동'), ('flexibility', '유연성 운동'), ('balance', '균형 운동'), ('general', '일반 운동')], default='general', max_length=20)),
                ('duration', models.IntegerField(help_text='운동 시간 (초)', validators=[django.core.validators.MinValueValidator(1)])),
                ('rep_count', models.IntegerField(default=0, help_text='반복 횟수')),
                ('average_score', models.FloatField(help_text='평균 자세 점수 (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_frames', models.IntegerField(default=0, help_text='분석된 프레임 수')),
                ('calories_burned', models.FloatField(default=0, help_text='소모 칼로리')),
                ('key_feedback', models.JSONField(default=list, help_text='주요 피드백 목록')),
                ('muscle_groups', models.JSONField(default=list, help_text='타겟 근육 그룹')),
                ('angle_scores', models.JSONField(blank=True, default=dict, help_text='관절별 평균 점수')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '운동 결과',
                'verbose_name_plural': '운동 결과',
                'db_table': 'workout_results',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='workout_res_user_id_e4f1d3_idx'), models.Index(fields=['exercise_name', '-created_at'], name='workout_res_exercis_ae58af_idx')],
            },
        ),
    ]
