# Generated by Django 4.2.7 on 2024-06-27 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='업적 고유 코드', max_length=50, unique=True)),
                ('title', models.CharField(max_length=100, verbose_name='업적명')),
                ('description', models.TextField(verbose_name='설명')),
                ('points', models.IntegerField(default=10, verbose_name='포인트')),
                ('category', models.CharField(choices=[('exercise', '운동'), ('nutrition', '영양'), ('social', '소셜'), ('streak', '연속'), ('milestone', '이정표'), ('general', '일반')], default='general', max_length=20)),
                ('icon', models.CharField(default='🏆', help_text='이모지 아이콘', max_length=10)),
                ('condition_type', models.CharField(blank=True, help_text='조건 타입', max_length=50)),
                ('condition_value', models.JSONField(blank=True, default=dict, help_text='조건 값')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': '업적',
                'verbose_name_plural': '업적',
                'db_table': 'achievements',
                'ordering': ['category', 'points'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(unique=True, verbose_name='레벨')),
                ('title', models.CharField(max_length=50, verbose_name='칭호')),
                ('required_points', models.IntegerField(verbose_name='필요 포인트')),
                ('icon', models.CharField(default='⭐', help_text='레벨 아이콘', max_length=10)),
                ('color', models.CharField(default='#FFD700', help_text='레벨 색상 (HEX)', max_length=7)),
            ],
            options={
                'verbose_name': '레벨',
                'verbose_name_plural': '레벨',
                'db_table': 'levels',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0, verbose_name='총 포인트')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='achievements.level')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='level_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 레벨',
                'verbose_name_plural': '사용자 레벨',
                'db_table': 'user_levels',
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_unlocked', models.BooleanField(default=False, verbose_name='달성 여부')),
                ('unlocked_at', models.DateTimeField(blank=True, null=True, verbose_name='달성 시간')),
                ('progress', models.FloatField(default=0, verbose_name='진행률 (0-100)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='추가 메타데이터')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 업적',
                'verbose_name_plural': '사용자 업적',
                'db_table': 'user_achievements',
                'ordering': ['-unlocked_at', 'achievement__category'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('user', 'achievement')},
        ),
    ]
