# Generated by Django 5.0.1 on 2025-06-05 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('남성', '남성'), ('여성', '여성')], max_length=10)),
                ('experience_level', models.IntegerField(choices=[(1, 'Lv.1 완전 처음이에요.'), (2, 'Lv.2 초보지만 경험 있어요.'), (3, 'Lv.3 익숙해지고 있어요.'), (4, 'Lv.4 잘해요.')])),
                ('goal', models.CharField(max_length=100)),
                ('custom_goal', models.CharField(blank=True, max_length=20, null=True)),
                ('workout_days_per_week', models.IntegerField()),
                ('weight_unit', models.CharField(default='kg', max_length=5)),
                ('distance_unit', models.CharField(default='km', max_length=5)),
                ('referral_source', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MusicPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_type', models.CharField(max_length=50)),
                ('mood', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('artist', models.CharField(blank=True, max_length=100)),
                ('playlist_url', models.URLField(blank=True)),
                ('keywords', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'workout_type', 'mood')},
            },
        ),
        migrations.CreateModel(
            name='WorkoutRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('workout_type', models.CharField(max_length=50)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('distance', models.FloatField(blank=True, help_text='Distance in km', null=True)),
                ('calories_burned', models.IntegerField(blank=True, null=True)),
                ('start_latitude', models.FloatField(blank=True, null=True)),
                ('start_longitude', models.FloatField(blank=True, null=True)),
                ('end_latitude', models.FloatField(blank=True, null=True)),
                ('end_longitude', models.FloatField(blank=True, null=True)),
                ('route_coordinates', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songs_played', models.JSONField(default=list)),
                ('feedback', models.CharField(blank=True, choices=[('liked', 'Liked'), ('neutral', 'Neutral'), ('disliked', 'Disliked')], max_length=20, null=True)),
                ('music_preference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.musicpreference')),
                ('workout_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_played', to='api.workoutrecord')),
            ],
        ),
    ]
