# Generated by Django 4.2.7

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),  # 이전 마이그레이션 파일 이름으로 변경 필요
    ]

    operations = [
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1, help_text='현재 레벨 (1-100)')),
                ('experience_points', models.IntegerField(default=0, help_text='총 경험치')),
                ('total_achievement_points', models.IntegerField(default=0, help_text='총 업적 포인트')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='level_info', to=settings.AUTH_USER_MODEL)),
                ('main_achievements', models.ManyToManyField(blank=True, help_text='대표 업적 (최대 3개)', related_name='featured_by', to='api.userachievement')),
            ],
            options={
                'verbose_name': '사용자 레벨',
                'verbose_name_plural': '사용자 레벨 목록',
            },
        ),
    ]
