# Generated by Django 5.2 on 2025-06-13 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_exercise_remove_workoutmusic_music_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='description_en',
            field=models.TextField(blank=True, help_text='영어 설명', null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='description_es',
            field=models.TextField(blank=True, help_text='스페인어 설명', null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscle_group_en',
            field=models.CharField(blank=True, help_text='영어 근육군', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscle_group_es',
            field=models.CharField(blank=True, help_text='스페인어 근육군', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='name_en',
            field=models.CharField(blank=True, help_text='영어 이름', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='name_es',
            field=models.CharField(blank=True, help_text='스페인어 이름', max_length=100, null=True),
        ),
    ]
