# Generated by Django 5.2.1 on 2025-06-16 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_exercise_description_en_exercise_description_es_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('name_es', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_es', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('workout', '운동'), ('nutrition', '영양'), ('streak', '연속'), ('milestone', '마일스톤'), ('challenge', '챌린지')], max_length=20)),
                ('badge_level', models.CharField(choices=[('bronze', '브론즈'), ('silver', '실버'), ('gold', '골드'), ('platinum', '플래티넘'), ('diamond', '다이아몬드')], default='bronze', max_length=20)),
                ('icon_name', models.CharField(help_text='Badge icon identifier', max_length=50)),
                ('target_value', models.IntegerField(help_text='목표 달성 값')),
                ('points', models.IntegerField(default=10, help_text='획득 포인트')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '업적',
                'verbose_name_plural': '업적 목록',
                'ordering': ['category', 'target_value'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0, help_text='현재 진행 상황')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 업적',
                'verbose_name_plural': '사용자 업적 목록',
                'ordering': ['-completed', '-progress'],
                'unique_together': {('user', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='UserGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('daily_calories', '일일 칼로리 목표'), ('weekly_workouts', '주간 운동 횟수'), ('monthly_workouts', '월간 운동 횟수'), ('weight_target', '목표 체중'), ('daily_steps', '일일 걸음수'), ('daily_water', '일일 수분 섭취'), ('sleep_hours', '수면 시간')], max_length=30)),
                ('target_value', models.FloatField()),
                ('current_value', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 목표',
                'verbose_name_plural': '사용자 목표 목록',
                'ordering': ['goal_type'],
                'unique_together': {('user', 'goal_type')},
            },
        ),
    ]
