# Generated by Django 5.2 on 2025-06-18 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_add_user_level'),
        ('api', '0004_achievement_userachievement_usergoal'),
    ]

    operations = [
    ]
