# Generated by Django 5.2 on 2025-06-25 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_achievement_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userworkoutachievement',
            options={'ordering': ['-completed', '-progress'], 'verbose_name': '사용자 운동 기록', 'verbose_name_plural': '사용자 운동 기록 목록'},
        ),
        migrations.AlterModelOptions(
            name='userworkoutlevel',
            options={'verbose_name': '사용자 운동 레벨', 'verbose_name_plural': '사용자 운동 레벨 목록'},
        ),
        migrations.AlterModelOptions(
            name='workoutachievement',
            options={'ordering': ['category', 'target_value'], 'verbose_name': '운동 기록 업적', 'verbose_name_plural': '운동 기록 업적 목록'},
        ),
        migrations.AlterField(
            model_name='userworkoutachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userworkoutlevel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workout_level_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
