# Generated by Django 5.2 on 2025-06-23 02:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='운동명')),
                ('name_en', models.CharField(max_length=100, verbose_name='영문명')),
                ('category', models.CharField(choices=[('upper', '상체'), ('lower', '하체'), ('core', '코어'), ('fullbody', '전신')], max_length=50, verbose_name='카테고리')),
                ('difficulty', models.CharField(choices=[('beginner', '초급'), ('intermediate', '중급'), ('advanced', '고급')], max_length=20, verbose_name='난이도')),
                ('description', models.TextField(verbose_name='설명')),
                ('target_muscles', models.JSONField(default=list, verbose_name='타겟 근육')),
                ('angle_calculations', models.JSONField(default=dict, verbose_name='각도 계산 설정')),
                ('key_points', models.JSONField(default=list, verbose_name='핵심 포인트')),
                ('icon', models.CharField(default='💪', max_length=10, verbose_name='아이콘')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '운동',
                'verbose_name_plural': '운동 목록',
                'ordering': ['category', 'difficulty', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('realtime', '실시간'), ('upload', '업로드')], max_length=20, verbose_name='분석 모드')),
                ('duration', models.FloatField(default=0, verbose_name='운동 시간(초)')),
                ('rep_count', models.IntegerField(default=0, verbose_name='반복 횟수')),
                ('average_score', models.FloatField(default=0, verbose_name='평균 점수')),
                ('max_score', models.FloatField(default=0, verbose_name='최고 점수')),
                ('min_score', models.FloatField(default=0, verbose_name='최저 점수')),
                ('total_frames', models.IntegerField(default=0, verbose_name='총 프레임 수')),
                ('feedback_summary', models.JSONField(default=dict, verbose_name='피드백 요약')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='pose_analysis/videos/', verbose_name='비디오 파일')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일시')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pose_analysis.exercise', verbose_name='운동')),
            ],
            options={
                'verbose_name': '분석 세션',
                'verbose_name_plural': '분석 세션 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField(verbose_name='타임스탬프(초)')),
                ('frame_index', models.IntegerField(verbose_name='프레임 인덱스')),
                ('angles', models.JSONField(verbose_name='관절 각도')),
                ('scores', models.JSONField(verbose_name='부위별 점수')),
                ('overall_score', models.FloatField(verbose_name='전체 점수')),
                ('feedback', models.JSONField(default=list, verbose_name='피드백')),
                ('corrections', models.JSONField(default=list, verbose_name='교정 사항')),
                ('is_in_position', models.BooleanField(default=False, verbose_name='올바른 자세')),
                ('rep_phase', models.CharField(blank=True, max_length=20, null=True, verbose_name='운동 단계')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='pose_analysis.analysissession', verbose_name='세션')),
            ],
            options={
                'verbose_name': '프레임 분석',
                'verbose_name_plural': '프레임 분석 목록',
                'ordering': ['session', 'frame_index'],
            },
        ),
        migrations.CreateModel(
            name='UserExerciseStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sessions', models.IntegerField(default=0, verbose_name='총 세션 수')),
                ('total_reps', models.IntegerField(default=0, verbose_name='총 반복 횟수')),
                ('total_duration', models.FloatField(default=0, verbose_name='총 운동 시간(초)')),
                ('best_score', models.FloatField(default=0, verbose_name='최고 점수')),
                ('average_score', models.FloatField(default=0, verbose_name='평균 점수')),
                ('last_session_date', models.DateTimeField(blank=True, null=True, verbose_name='마지막 운동일')),
                ('improvement_rate', models.FloatField(default=0, verbose_name='향상률(%)')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pose_analysis.exercise', verbose_name='운동')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 운동 통계',
                'verbose_name_plural': '사용자 운동 통계',
                'ordering': ['user', 'exercise'],
                'unique_together': {('user', 'exercise')},
            },
        ),
    ]
