# Generated by Django - Merge migration

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pose_analysis', '0002_analysissession_guest_id_alter_analysissession_user'),
        ('pose_analysis', '0002_add_elite_exercises'),
    ]

    operations = [
        # 병합 마이그레이션 - 작업 없음
    ]
