# Generated by Django 5.2.3 on 2025-07-02 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('image_base64', models.TextField(blank=True, null=True)),
                ('calories', models.IntegerField()),
                ('protein', models.FloatField(help_text='단백질 (g)')),
                ('carbohydrates', models.FloatField(help_text='탄수화물 (g)')),
                ('fat', models.FloatField(help_text='지방 (g)')),
                ('fiber', models.FloatField(blank=True, help_text='식이섬유 (g)', null=True)),
                ('sugar', models.FloatField(blank=True, help_text='당류 (g)', null=True)),
                ('sodium', models.FloatField(blank=True, help_text='나트륨 (mg)', null=True)),
                ('analysis_summary', models.TextField()),
                ('recommendations', models.TextField()),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '음식 분석',
                'verbose_name_plural': '음식 분석 목록',
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyNutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_calories', models.IntegerField(default=0)),
                ('total_protein', models.FloatField(default=0)),
                ('total_carbohydrates', models.FloatField(default=0)),
                ('total_fat', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_nutrition', to=settings.AUTH_USER_MODEL)),
                ('food_analyses', models.ManyToManyField(to='api.foodanalysis')),
            ],
            options={
                'verbose_name': '일일 영양 기록',
                'verbose_name_plural': '일일 영양 기록 목록',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
