# Generated by Django 5.2.3 on 2025-07-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile_daily_steps_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='supabase_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Supabase user ID', null=True, unique=True),
        ),
    ]
